apiVersion: v1
kind: Service
metadata:
  name: konga-proxy
spec:
  type: NodePort
  ports:
  - name: konga
    port: 1337
    targetPort: 1337
    protocol: TCP
  selector:
    app: kong
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
          - name: DB_ADAPTER
            value: 'postgres'
          - name: DB_HOST
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: ""
        ports:
        - name: konga
          containerPort: 1337
          protocol: TCP
