kind: Service
apiVersion: v1
metadata:
  name: ms-puntos
spec:
  selector:
    app: ms-puntos
  ports:
    - name: http
      protocol: TCP
      nodePort: 32001
      port: 8080
      targetPort: 8080
  type: NodePort
